#include <stdio.h>
#include <stdlib.h>
#include "mrl.h"
#include "yaml_parser.h"

/* External Bison debug variable (generated by Bison with %define parse.trace) */
extern int yydebug;

int main(int argc, char **argv) {
    setvbuf(stdout, NULL, _IONBF, 0);

    /* Enable parser tracing if YYDEBUG environment variable is set */
    if (getenv("YYDEBUG")) {
        yydebug = 1;
    }

    Alphabet *a = NULL;
    Grammar *g = NULL;
    StringDiagram *sd = NULL;

    /* Use the standard entry point */
    int res = yaml_parse(&a, &g, &sd);
    
    if (sd) {
        ParseOutput output = {a, g, sd};
        rml_print_events(&output);
        
        free_stringdiagram(sd);
        free_grammar(g);
        free_alphabet(a);
    }
    
    if (res != EXIT_SUCCESS) {
        if (!sd) {
            fprintf(stderr, "Parse failed with code %d\n", res);
        }
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
